### PR TITLE
Added support for universal multi-boot for all AML s9xxx

### PR DESCRIPTION
**Pull request by 150balbes**
Added script aml_autoscript and s905_autoscript support for universal multi-boot for all image AML s9xxx. 
After you capture the image you want to rename the desired file dtb to the "dtb.img". You can start the system from SD and USB media.

### CODE REVIEW

**Comment by koenkooi** [comment]
So if I understand correctly, the image as-is, won't work and requires a manual rename for the dtb? Why not use the dtb for the current MACHINE as default?

**Comment by 150balbes** [comment]
This commit is primarily aimed at building "complex" images (where there are DTB for several or all models in the group).  The logic of the script s905_autoscript. If there is in /BOOT no "dtb.img", the script tries to use the built-in EMMC variant of dtb data. Therefore, the manual addition of dtb is needed in two cases. 1. If the dtb in the eMMC is not suitable for the current kernel. 2. If the image contains several variants of dtb for different variants of models. I agree, it is desirable to add the procedure of copying the required dtb immediately with the name "dtb.img" to the procedure of assembling image variants for specific models (where only one dtb file is used). This will facilitate the rest of the logic of using dtb data. By the way, it is desirable in the procedure of forming the file "extlinux.conf" to use the common name "dtb.img", then this configuration can be unified for all images (models).

example

https://github.com/superna9999/meta-meson/blob/sumo/conf/machine/khadas-vim.conf#L18

UBOOT_EXTLINUX_FDT = "../meson-gxl-s905x-khadas-vim.dtb"
to
UBOOT_EXTLINUX_FDT = "../dtb.img"

**Comment by 150balbes** [comment]
Question to the experts What I'm doing wrong. How to write a command in the recipe (or what else you need to add) to execute such a scenario. I have it gives an error (does not find the zip utility in the compilation procedure).


DEPENDS = "u-boot-mkimage-native zip"

SRC_URI += "file://aml_autoscript.cmd"
SRC_URI += "file://aml_autoscript.zip"

inherit deploy

S = "${WORKDIR}"

do_compile() {
	mkimage -A arm64 -O linux -T script -C none -a 0 -e 0 -n "aml_autoscript" -d ${WORKDIR}/aml_autoscript.cmd ${B}/aml_autoscript
        zip ${B}/aml_autoscript.zip ${B}/aml_autoscript
}

do_deploy() {
	install ${B}/aml_autoscript ${DEPLOYDIR}/aml_autoscript
        install ${B}/aml_autoscript.zip ${DEPLOYDIR}/aml_autoscript.zip
}

addtask deploy before do_build after do_compile

**Comment by koenkooi** [comment]
'zip' is for the target, 'zip-native' is for the host. Also, don't do 
```
FOO += "bar"
FOO += "baz"
```

but do

```
FOO = "bar \
             baz"
```

+= is a heavy operation during parsing and here you just want 2 files in SRC_URI. 

Doesn't deploy.bbclass already do the addtask for you?

**Comment by 150balbes** [comment]
Thanks,I'll check it out.

**Comment by 150balbes** [comment]
This line is wrong, I forgot to delete it after checking different options.
SRC_URI += "file://aml_autoscript.zip"

**Comment by 150balbes** [comment]
For these parameters, this option is also preferable ?

+EXTRA_IMAGEDEPENDS += " s905-autoscript"
+EXTRA_IMAGEDEPENDS += " s905-autoscript-multiboot"
+IMAGE_BOOT_FILES += " s905_autoscript"
+IMAGE_BOOT_FILES += " aml_autoscript"
+IMAGE_BOOT_FILES += " aml_autoscript.zip"

to

+EXTRA_IMAGEDEPENDS += " s905-autoscript \
             s905-autoscript-multiboot"
+IMAGE_BOOT_FILES += " s905_autoscript \
              aml_autoscript \
              aml_autoscript.zip"

**Comment by koenkooi** [comment]
Yes and check if you really need to append (+=) or can just overwrite it (=).

**Comment by superna9999** [comment]
Hi @150balbes,

Please do not add the logic in meson64.inc, I do not want to generalize this to all boards.
The boards support by mainline u-boot (khadas-vim, libretech-cc, nanopi-k2 and odroidc2) should use the normal dtb name and use the extlinux boot method.
These boards have a -sdboot variant to use them with the amlogic u-boot.
So you can add a specific include for all the boards aimed to be booted with the amlogic u-boot.
For the "dtb.img" name, I bypassed it easily by customizing the s905_autoscript before deploying it, you should do the same.
For the s9xxx i fear there is no clean solution since most of the board uses the default p212 or p23x amlogic u-boot board model...

**Comment by 150balbes** [comment]
I do not impose anything on how to do you decide for yourself. Written below, it is only information. :)

You proceed from the premise that the device does not have a u-boot loader (a device without built-in eMMC\NAND memory or a device with internal memory, but the loader was forced to be removed), so you need your own boot loader to start the system. By the way, erasing the bootloader from internal memory to run an external system is a bad practice. :) Why remove the bootloader if you can easily start the system from any external media without removing the built-in bootloader and risk getting a brick ? Let's look at several startup scenarios (for example, Yocto) from any external media on Amlogic. 1. The first group of devices. All TV boxes, VIM\VIM2, LibreComputer and other similar models with connected eMMC module (with configured working system in eMMC). All these devices have their own working u-boot (no matter which version) and eMMC has already configured working system. The task, without breaking the existing system, is to quickly start another system from external media. Write a test image to any (SD or USB) media. Once activate the multiload. Connect it to the device and turn on the power. The system will automatically start from external media. After the tests, disconnect the media and start up, the former working system. As new variants of the test system are released, it is enough for the user to write a new variant on the medium and he will be able to quickly check it, without the risk of disrupting the operation of the working system. 2. The second group of devices. Which do not have built-in memory. The system was written to the media and when you start u-boot starts from the image, for example, version 2018, it spelled out the standard procedure for starting (using the file extlinux.conf), the presence of three not large multi-start script files does not affect the start of the system in this version. That is, you can use the same image on any group of devices. The startup algorithm will be automatically determined by the initial state of the device. For example, I have recorded a Yocto image with a new u-boot 2018 built-in on my SD card, I have a VIM, I have a working system configured in eMMC (with activated multi-boot), and I don't want to break it (erase u-boot). When you connect the SD card with the test system, the multi-start script is automatically used. And I'm quietly testing the new system from an external medium. If I want to test the new u-boot 2018, I'll erase the regular u-boot eMMC and automatically launch u-boot 2018 from the SD card from the test image. The presence of three small files only expand the options for starting the system, without interfering with the use of the former version using u-boot from the yocto image.

Regarding the use of the unified name " dtb.img". Why complicate the logic of the Assembly (add many of the same type of lines in each configuration), if you can do a single universal option ? By the way, if you specify "extlinux.conf", one common name"../ dtb.img " can easily use the new u-boot 2018 to build an image for all models, such as p212, and the user will be enough, after recording the image, only to select your option dtb and rename it to "dtb.img". When you start, u-boot 2018 will automatically use the correct file for the selected model.

**Comment by 150balbes** [comment]
Forgot to mention another option for LePotato. :) 
Working system on SD card and need to run the test system with USB (not pulling out SD card). In the presence of a script multiboot, it is easy to operate.

**Comment by superna9999** [comment]
Hi @150balbes, thanks for answering

I'm not against all this, I just want to make "pure" image for fully mainline supported boards, without all the amlogic specific tricks. And the "pure" images don't have a FAT32 first partition, because having a FAT32 partition is no more necessary when you have mainline U-boot.

It's ok to enable multiboot all *all* machines except the khadas-vim.conf, libretech-cc.conf, odroidc2.conf, p212.conf and nanopi-k2.conf, but it's ok to enable this on the -sdboot.conf variant of these.

For the dtb.conf sorry I'm not conviced at all... it's an ugly simplification. The name of the dtb has a signification.

BTW please remove my aml-autoscript implementation and use my trick to personalize with the board DTB name, because this is the way it should be done.

**Comment by superna9999** [comment]
And thanks for posting a clean version of aml/s905_autoscript, it's really useful !!! mine was really bad...

**Comment by 150balbes** [comment]
I'm sorry, but I'm not sure what you want as a result ? 
I suggest this option. 
1. To close this pull-request. 
2. Move add-ons for installation of scripts from the file amlogic-meson64.inc in conf/machine/amlogic-s9xxx.conf (where many DTB are used and there is a FAT partition). 
3. The recipe aml-autoscript replace the original file/aml_autoscript.cmd on s905_autoscript and edit its content. Recipe aml-autoscript is already registered in all the necessary configuration.

**Comment by superna9999** [comment]
@150balbes sorry, don't close it, I just want you to modify this PR to avoid modifying the khadas-vim.conf, libretech-cc.conf, odroidc2.conf, p212.conf and nanopi-k2.conf, by adding a separate conf include for other boards configurations. Apart that, it's ok

**Comment by 150balbes** [comment]
I want to make another request, with new fixes (I made additional improvements on the Koenkoi prompt).

**Pull request closed without merging**
