### PR TITLE
Added support for universal multi-boot for image s9xxx

### PR DESCRIPTION
**Pull request by 150balbes**

### CODE REVIEW

**Comment by superna9999** [comment]
Cool, thanks @150balbes, can you make a single commit ? and I merge it

**Comment by koenkooi** [comment]
FWIW, the dropdown on the green "merge pull request" button has a 'squash and merge' option.

**Comment by superna9999** [comment]
@koenkooi forgot this, thanks ;-)
LGTM !

**Comment by 150balbes** [comment]
@koenkooi Thank you, I didn't know there was ...

**Pull request merged**
