### PR TITLE
Add support for Libretech AC AML-S805X-AC also known as La Frite in Warrior

### PR DESCRIPTION
**Pull request by leon-anavi**
Hi,

Long ago I backed the crowdfunding campaign of ["La Frite: Open Source Fries"](https://www.kickstarter.com/projects/librecomputer/la-frite-open-source-fries). After a huge delay my 1GB version of  Libretech AC AML-S805X-AC was delivered and after spending some efforts I was able to bring up core-image-minimal booted from a USB stick. The changes in the provided GitHub PR feature:

* New machine configuration for Libretech AC AML-S805X-AC also known as La Frite
* Update U-Boot version to support the board
* Add a patch to the kernel to provide device tree for Libretech AC AML-S805X-AC
* Support libretech-ac in amlogic-fip-prebuilt.bb using the same configurations as for libretech-cc

Best regards, Leon

### CODE REVIEW

**Comment by superna9999** [comment]
Hi @leon-anavi !

Nice work, looks very good !

Currently the warrior branch should be in sync with master branch (the next of warrior is master until a new yocto/oe version is tagged), but it's not and it's my bad...

Let me sync all this and merge this PR into master and sync the warrior branch, no need for #65 !

Neil

**Comment by leon-anavi** [comment]
Hi @superna9999,

Thanks for the quick feedback! Noted for master and warrior. In the mean time I will give Thud a try and if everything is OK with it I will make a PR for it too.

Thanks,
Leon

**Comment by superna9999** [comment]
> Hi @superna9999,
> 
> Thanks for the quick feedback! Noted for master and warrior. In the mean time I will give Thud a try and if everything is OK with it I will make a PR for it too.
> 
> Thanks,
> Leon

Sure, thanks for working on this

**Comment by leon-anavi** [comment]
> Sure, thanks for working on this

Done https://github.com/superna9999/meta-meson/pull/66 :) 

Best regards, Leon

**Pull request merged**
