### PR TITLE
s905-autoscript-multiboot: Fix conflict deployment

### PR DESCRIPTION
**Pull request by dagmcr**
When building aml images for s9xxx machines the aml_autoscript is deployed
by 2 different recipes: s905-autoscript-multiboot and aml-autoscript.
Since aml-autoscript is the generic one, rename the file in
s905-autoscript-multiboot to fix this error:

ERROR: s905-autoscript-multiboot-1.0-r0 do_deploy_setscene: The recipe s905-autoscript-multiboot is trying to install files into a shared area when those files already exist. Those files and their manifest location are:
  /workdir/build/tmp/deploy/images/libretech-ac/aml_autoscript
    (matched in manifest-libretech_ac-aml-autoscript.deploy)
Please verify which recipe should provide the above files.

Signed-off-by: Daniel Gomez <dagmcr@gmail.com>

### CODE REVIEW

**Comment by superna9999** [comment]
Hi,

In fact the `s905-autoscript-multiboot` is the correct one, and the filename "aml_autoscript" and "aml_autoscript.zip" are expected by the amlogic u-boot, so in fact the `aml-autoscript` should be removed...

**Comment by dagmcr** [comment]
Thanks for the clarification. I wasn't sure so I kept both. I will do the PR with the changes.

**Comment by dagmcr** [comment]
Hi @superna9999, 

I've updated the PR with the changes:

*  Removing this two files:
`recipes-bsp/aml-autoscript/aml-autoscript.bb`
`recipes-bsp/aml-autoscript/files/aml_autoscript.cmd`

*  Replace `aml-autoscript` dependencies with the generic recipe for the s905.

**Comment by superna9999** [comment]
Nice, thanks for the work

**Pull request merged**
